/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rsriv1' at '07/03/17 15:49' with Gradle 2.14.1
 *
 * @author rsriv1, @date 07/03/17 15:49
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
